# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Keigo Tada
# title: Graduate school of Information Science and Engineering, Ritsumeikan University 
email: is0463hx@ed.ritsumei.ac.jp
# address: 1-1-1 Nojihigashi, Kusatsu, Shiga 525-8577, Japan
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Research Themes # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
      <h2 style="text-align:center"><font size=4><b>Computational Neuroscience: </b> Retinal neural circuit/Retinitis Pigmentosa/Photopsia
      <h2 style="text-align:center"><font size=4><b>Machine Learning: </b> Out-of-Distribution Generalization/Uncertainty/Calibration

    # content:
    #   - layout: list
    #     title: Computational Neuroscience
    #     description: ttt

    #     title: Machine Learning
    #     description: ttt
        # - subtitle: Computational Neuroscience
        #   description: ttt
        # - subtitle: Machine Learning
        #   description: rrrr
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        # description: | # this will include new lines to allow paragraphs
        #   I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ritsumeikan University 
        caption: Apr.2018 - Mar.2022, Apr.2022 -
        sub_title: BA & MA Information Science and Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          <font size=3><b>Advisor:</b> Katsunori Kitano
          <br><font size=3><b>Topics:</b> retinitis pigmentosa/photopsia/Spontaneous Oscillation
          <br><font size=3><b>Lab:</b> <a href="https://cns.ci.ritsumei.ac.jp"></a>

  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Computational Neuroscience
        # link: boringcompany.com
        # link_text: boringcompany.com
        description: | # this will include new lines to allow paragraphs
            <h2 style="text-align:left"><font size=3><b>A Computational Model for Spontaneous Oscillation in Retinitis Pigmentosa</b>
            <br><i><u>Keigo Tada</u></i>, <i>Katsunori Kitano</i>, The 46th Annual Meeting of the Japan Neuroscience Society (ARVO), 2023.

            <br><h2 style="text-align:left"><font size=3><b>A computational model for normal and pathological activity of the retinal circuit</b>
            <br><i><u>Keigo Tada</u></i>, <i>Katsunori Kitano</i>, The Association for Research in Vision and Ophthalmology, 2023.
          

      - layout: left
        title: Machine Learning
        # link: boringcompany.com
        # link_text: boringcompany.com
        description: | # this will include new lines to allow paragraphs
            <h2 style="text-align:left"><font size=3><b>How Image Corruption and Perturbation Affect Out-Of-Distribution Generalization and Calibration</b>
            <br><i><u>Keigo Tada</u></i>, <i>Hiroki Naganuma</i>, International Joint Conference on Neural Networks (IJCNN), 2023.

            <br><h2 style="text-align:left"><font size=3><b>Measuring the Effect of Image Corruption and Perturbation through the Lens of Calibration and OOD</b>
            <br><i><u>Keigo Tada</u></i>, <i>Hiroki Naganuma</i>, The 85th National Convention of Information Processing Society of Japan (IPSJ), 2023.

            <br><h2 style="text-align:left"><font size=3><b>Effect of Distribution Shift on Out-of-Distribution Generalization and Uncertainty</b>
            <br><i><u>Keigo Tada</u><sup>#</sup></i>, <i>Hiroki Naganuma<sup>#</sup></i>, Forum for Information and Technology 2022 (FIT2022), 2022. # denotes equal contribution

  - title: Internship # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hutzper Inc.
        link: https://hutzper.com
        # link_text: boringcompany.com
        sub_title: AI(computer vision) engineer
        caption: Dec. 2020 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            AI development, PoC

  - title: Scholarship
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Academic Excellence Scholarship for 1st Year of Enrollment

  - title: Others
    layout: text
    content: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
